# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHm5RwnPYV4QdS0fXPzgte_GrOZH33RN
"""

!pip install biopython

from Bio import SeqIO
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

record=SeqIO.read('sequence.fasta','fasta')
sequence = str(record.seq)
def extract_kmers(seq,k):
  kmers = []
  for i in range(len(seq) - k + 1):
      kmers.append(seq[i:i+k])
      return kmers
k=3
kmers=extract_kmers(sequence,k)
kmer_counts = Counter(kmers)
window_size=100
step_size=10
heat_values=[]
for i in range(0,len(sequence)-window_size+1,step_size):
  window_seq= sequence[i:i+window_size]
  window_kmers=extract_kmers(window_seq,k)
  freq = 0
  for kmer in window_kmers:
    freq += kmer_counts[kmer]
  heat_values.append(freq)
heatmap_of_Array=np.array(heat_values).reshape(1,-1)
plt.figure(figsize=(20,10))
sns.heatmap(heatmap_of_Array,cmap="coolwarm",cbar=True,xticklabels=False,
            yticklabels=False)
print("Max score:", max(heat_values))
print("Min score:", min(heat_values))

plt.title(f"HeatMap of {k}-mer frequencies in the DNA")
plt.xlabel("Sliding Window Position")
plt.tight_layout()
plt.show()

